sudo: required
language: java
jdk: openjdk10

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

git:
  depth: 9999999

addons:
  sonarcloud:
    organization: "joostlek-github"
    token: $SONAR_TOKEN

script:
  - mvn clean package sonar:sonar -Dsonar.projectKey=joostlek_richrail -Dsonar.organization=joostlek-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
